import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import 'primeicons/primeicons.css';
import "primereact/resources/themes/lara-light-cyan/theme.css";
import { PrimeReactProvider } from 'primereact/api';
import Footer from "@components/Footer";
import Head from "next/head";
import { Menubar } from 'primereact/menubar';
import items from '@config/items';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PrimeReactProvider>
          <Head>
            <link id="theme-link" rel="stylesheet" href="/themes/soho-dark/theme.css" />
          </Head>
          <div className={styles.page}>
            <Menubar model={items} />  
            {children} 
          </div>
          <Footer />
        </PrimeReactProvider>
      </body>
    </html>
  );
}
